import React, { useState } from 'react';
import { Download, FileText, Table, Printer, Check, Share2 } from 'lucide-react';

export default function ExportToolbar({ result }) {
  if (!result) return null;

  const [copied, setCopied] = useState(false);

  // 1. Export as Printable / PDF
  const handlePrint = () => {
    window.print();
  };

  // 2. Export as Markdown Financial Memo
  const handleDownloadMarkdown = () => {
    const { question, synthesis_report, extracted_facts = [], computations = {} } = result;
    const now = new Date().toISOString().split('T')[0];

    let md = `# Filing Sleuth — SEC EDGAR Forensic Research Report\n\n`;
    md += `**Date:** ${now}\n`;
    md += `**Question:** ${question}\n\n`;

    if (synthesis_report) {
      if (synthesis_report.fiscal_mismatch_warning) {
        md += `> ⚠️ **FISCAL YEAR MISMATCH:** ${synthesis_report.fiscal_mismatch_warning}\n\n`;
      }

      md += `## Executive Summary\n${synthesis_report.executive_summary}\n\n`;

      if (synthesis_report.comparison_matrix && synthesis_report.comparison_matrix.length > 0) {
        md += `## Comparison Matrix\n`;
        const headers = Object.keys(synthesis_report.comparison_matrix[0]);
        md += `| ${headers.join(' | ')} |\n`;
        md += `| ${headers.map(() => '---').join(' | ')} |\n`;
        synthesis_report.comparison_matrix.forEach((row) => {
          md += `| ${headers.map((h) => row[h] ?? '—').join(' | ')} |\n`;
        });
        md += `\n`;
      }

      if (synthesis_report.key_findings && synthesis_report.key_findings.length > 0) {
        md += `## Key Findings\n`;
        synthesis_report.key_findings.forEach((f) => {
          md += `### ${f.claim}\n`;
          if (f.company) md += `**Entity:** ${f.company} (${f.ticker || '—'})\n`;
          if (f.metric) md += `**Concept:** \`${f.metric}\`\n`;
          if (f.value !== null && f.value !== undefined) {
            md += `**Reported Value:** ${f.value.toLocaleString()} ${f.unit || ''}\n`;
          }
          if (f.exact_quote) {
            md += `> "${f.exact_quote}"\n`;
            md += `*Provenance: ${f.item_section || 'SEC Filing'} | Accession: ${f.accession_number || 'Official EDGAR'}*\n`;
          }
          md += `\n`;
        });
      }

      if (synthesis_report.citations && synthesis_report.citations.length > 0) {
        md += `## Citations & Audit Provenance\n`;
        synthesis_report.citations.forEach((c) => {
          md += `[${c.citation_id}] ${c.company} — ${c.form_type} (${c.item_section || 'EDGAR'})\n`;
          md += `Accession Number: ${c.accession_number} | Source Type: ${c.source_type}\n`;
          if (c.quote_verified !== null && c.quote_verified !== undefined) {
            md += `Quote Verified: ${c.quote_verified ? 'YES (100% Levenshtein Grounded)' : 'NO'}\n`;
          }
          md += `\n`;
        });
      }
    }

    md += `---\n*Generated by Filing Sleuth (SEC EDGAR Autonomous Forensic Agent)*\n`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Filing_Sleuth_Report_${now}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // 3. Export as Audit CSV
  const handleDownloadCSV = () => {
    const { extracted_facts = [] } = result;
    const now = new Date().toISOString().split('T')[0];

    const headers = [
      'Company',
      'Ticker',
      'Metric / Concept',
      'Fiscal Year',
      'Fiscal Period',
      'Value',
      'Unit',
      'Source Type',
      'Item Section',
      'Accession Number',
      'Confidence',
      'Quote Verified',
      'Exact Quote',
    ];

    const escapeCsv = (str) => {
      if (str === null || str === undefined) return '';
      const s = String(str).replace(/"/g, '""');
      return `"${s}"`;
    };

    const rows = extracted_facts.map((f) => [
      escapeCsv(f.company),
      escapeCsv(f.ticker),
      escapeCsv(f.metric),
      escapeCsv(f.fiscal_year),
      escapeCsv(f.fiscal_period),
      escapeCsv(f.value),
      escapeCsv(f.unit),
      escapeCsv(f.source_type),
      escapeCsv(f.item_section),
      escapeCsv(f.accession_number),
      escapeCsv(f.confidence),
      escapeCsv(f.quote_verified),
      escapeCsv(f.exact_quote),
    ]);

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Filing_Sleuth_Audit_Data_${now}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="export-toolbar-wrapper">
      <div className="export-actions">
        <button
          type="button"
          className="export-btn"
          onClick={handlePrint}
          title="Print or save as executive PDF with formal letterhead"
        >
          <Printer size={14} />
          <span>Print / PDF</span>
        </button>

        <button
          type="button"
          className="export-btn"
          onClick={handleDownloadMarkdown}
          title="Download complete research findings as Markdown memo"
        >
          <FileText size={14} />
          <span>Financial Memo (.md)</span>
        </button>

        <button
          type="button"
          className="export-btn"
          onClick={handleDownloadCSV}
          title="Export raw extracted facts and accession numbers to CSV"
        >
          <Table size={14} />
          <span>Audit Data (.csv)</span>
        </button>
      </div>
    </div>
  );
}
